# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.setEnabled(True)
        AdminWindow.resize(808, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup/img/admin/admin_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AdminWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(AdminWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 20, 731, 511))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        AdminWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AdminWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 25))
        self.menubar.setObjectName("menubar")
        self.menuTerminals = QtWidgets.QMenu(self.menubar)
        self.menuTerminals.setObjectName("menuTerminals")
        self.menuOrganizations_DB = QtWidgets.QMenu(self.menubar)
        self.menuOrganizations_DB.setObjectName("menuOrganizations_DB")
        self.menuReports = QtWidgets.QMenu(self.menubar)
        self.menuReports.setObjectName("menuReports")
        self.menuReports_2 = QtWidgets.QMenu(self.menubar)
        self.menuReports_2.setObjectName("menuReports_2")
        AdminWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AdminWindow)
        self.statusbar.setObjectName("statusbar")
        AdminWindow.setStatusBar(self.statusbar)
        self.actionTransactions_DB = QtWidgets.QAction(AdminWindow)
        self.actionTransactions_DB.setObjectName("actionTransactions_DB")
        self.actionAbout = QtWidgets.QAction(AdminWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(AdminWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionTransactions = QtWidgets.QAction(AdminWindow)
        self.actionTransactions.setObjectName("actionTransactions")
        self.actionTerminals = QtWidgets.QAction(AdminWindow)
        self.actionTerminals.setObjectName("actionTerminals")
        self.actionOrganizations = QtWidgets.QAction(AdminWindow)
        self.actionOrganizations.setObjectName("actionOrganizations")
        self.actionOrganization_Types = QtWidgets.QAction(AdminWindow)
        self.actionOrganization_Types.setObjectName("actionOrganization_Types")
        self.actionCollectors = QtWidgets.QAction(AdminWindow)
        self.actionCollectors.setObjectName("actionCollectors")
        self.actionTransactions_2 = QtWidgets.QAction(AdminWindow)
        self.actionTransactions_2.setObjectName("actionTransactions_2")
        self.actionBy_terminal = QtWidgets.QAction(AdminWindow)
        self.actionBy_terminal.setObjectName("actionBy_terminal")
        self.actionTimespan_by_terminal = QtWidgets.QAction(AdminWindow)
        self.actionTimespan_by_terminal.setObjectName("actionTimespan_by_terminal")
        self.menuTerminals.addAction(self.actionAbout)
        self.menuTerminals.addSeparator()
        self.menuTerminals.addAction(self.actionExit)
        self.menuOrganizations_DB.addAction(self.actionTransactions)
        self.menuOrganizations_DB.addAction(self.actionTerminals)
        self.menuReports.addAction(self.actionOrganizations)
        self.menuReports.addAction(self.actionOrganization_Types)
        self.menuReports.addAction(self.actionCollectors)
        self.menuReports_2.addAction(self.actionTransactions_2)
        self.menuReports_2.addAction(self.actionBy_terminal)
        self.menuReports_2.addAction(self.actionTimespan_by_terminal)
        self.menubar.addAction(self.menuTerminals.menuAction())
        self.menubar.addAction(self.menuOrganizations_DB.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())
        self.menubar.addAction(self.menuReports_2.menuAction())

        self.retranslateUi(AdminWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "Database administration"))
        self.pushButton.setText(_translate("AdminWindow", "Add record"))
        self.menuTerminals.setTitle(_translate("AdminWindow", "File"))
        self.menuOrganizations_DB.setTitle(_translate("AdminWindow", "Transactions DB"))
        self.menuReports.setTitle(_translate("AdminWindow", "Organizations DB"))
        self.menuReports_2.setTitle(_translate("AdminWindow", "Reports"))
        self.actionTransactions_DB.setText(_translate("AdminWindow", "Transactions DB"))
        self.actionAbout.setText(_translate("AdminWindow", "About"))
        self.actionExit.setText(_translate("AdminWindow", "Exit"))
        self.actionTransactions.setText(_translate("AdminWindow", "Transactions"))
        self.actionTerminals.setText(_translate("AdminWindow", "Terminals"))
        self.actionOrganizations.setText(_translate("AdminWindow", "Organizations"))
        self.actionOrganization_Types.setText(_translate("AdminWindow", "Organization Types"))
        self.actionCollectors.setText(_translate("AdminWindow", "Collectors"))
        self.actionTransactions_2.setText(_translate("AdminWindow", "Transactions"))
        self.actionBy_terminal.setText(_translate("AdminWindow", "By terminal"))
        self.actionTimespan_by_terminal.setText(_translate("AdminWindow", "Timespan by terminal"))

